### ISSUE TITLE
No abideCompile targets found

### ISSUE THREAD

**Issue by ArmorDarks** [mozilla/grunt-i18n-abide#43]
Hi

I'm having issues with `abideCompile` command under Windows 7 (gettext installed and added to env path).

Task:

``` coffee
  @config 'abideCompile':
    json:
      dest: "json/"
      options:
        type: "json"
        localeDir: "locale"
```

Structure:

![](http://i.imgur.com/oDeg3NZ.png)

In result I'm always receiving following error:

```
Running "abideCompile" task
>> No "abideCompile" targets found.
Warning: Task "abideCompile" failed. Use --force to continue.
```

I'm getting feeling that I'm missing something very obvious, but still can't figure out what exactly.

Maybe it has something to do with Windows paths? Windows using `\` as delimiter for paths, which may cause issues sometimes.

I would be thankful for any help

**Comment by muffinresearch** [comment]
This looks like the conf is broken somehow. That error message suggests that there's not a target defined. In a normal config this would be the target:

```js
  abideCompile: {
    json: { // This is the target
      dest: '/json/',
      options: {
        type: 'json',
        localeDir: 'tests/tmp',
      }
    },
    mo: {
      options: {
        type: 'mo',
        localeDir: 'tests/tmp',
      }
    }
  },
```

I've no idea about coffeescript but I think it might be something to do with that.

Here's a random Gruntfile.coffee example: https://github.com/benatkin/grunt-coffee-example/blob/master/Gruntfile.coffee which looks a bit different.

**Comment by ArmorDarks** [comment]
Oh my, how I could be so blind!

Actually, it didn't work due to `:` after the `@config` part. It had to be:

``` coffee
  @config 'abideCompile', #this is where it was wrong
    json:
      dest: "json/"
      options:
        type: "json"
        localeDir: "locale"
```

I was so sure that I've copied task correctly (since all other tasks worked fine) that even didn't think to check `@config` part.

Thanks for the help and sorry for taking your time on so stupid issue

**Comment by muffinresearch** [comment]
No problem, glad you got it sorted!
