### ISSUE TITLE
Extracting comments

### ISSUE THREAD

**Issue by ArmorDarks** [mozilla/grunt-i18n-abide#44]
Hi

It seems that extracting of comments as per [jsxgettext](https://github.com/zaach/jsxgettext) doesn't work for nunjucks

Comments like `{# L10n: This is comment #}` before `gettext` or on same line after it, should be extracted to `pot` according to jsxgettext documentation, but they aren't

Maybe it's because `-c` isn't pushed with `jsxgettext` for `abideExtract`?

**Comment by muffinresearch** [comment]
By default the comments should be processed by jsxgettext looking at https://github.com/zaach/jsxgettext/blob/master/lib/jsxgettext.js#L120 - I think this is a bug in the way the jsxgettext jinja parser works as it looks like it only processes text between '{{' and  '}}'.

**Comment by muffinresearch** [comment]
I've filed a jsxgettext issue https://github.com/zaach/jsxgettext/issues/86

**Comment by ArmorDarks** [comment]
Ah, I see.

Thanks a lot!
