### ISSUE TITLE
Bump npm version to 0.15?

### ISSUE THREAD

**Issue by gabceb** [mozilla/grunt-i18n-abide#45]
I get `Fatal error: Command "jsxgettext" doesn't exist! Maybe you need to install it.` with 0.14 which was fixed by https://github.com/mozilla/grunt-i18n-abide/commit/9fb600c8bfb8b335cc9f913bdc971cad6771a41c

**Comment by muffinresearch** [comment]
Sorry about that. 0.0.15 is now released.
